Repository spring-cloud/spring-cloud-kubernetes, pull requests merged in 2018-12, with the labels that each got.

#275 Doc improvements and fix 268
  docs/src/main/asciidoc/discovery-client.adoc
  docs/src/main/asciidoc/examples.adoc
  docs/src/main/asciidoc/kubernetes-awareness.adoc
  docs/src/main/asciidoc/leader-election.adoc
  docs/src/main/asciidoc/other-resources.adoc
  docs/src/main/asciidoc/pod-health-indicator.adoc
  docs/src/main/asciidoc/property-source-config.adoc
  docs/src/main/asciidoc/ribbon-integration.adoc
  docs/src/main/asciidoc/security-service-accounts.adoc
Labels: in progress

#265 Enable kubernetes discovery client on bootstrap stage.
  pom.xml
  spring-cloud-kubernetes-discovery/pom.xml
  spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientAutoConfiguration.java
  spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientBootstrapConfiguration.java
  spring-cloud-kubernetes-discovery/src/main/resources/META-INF/spring.factories
  spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryAutoConfigurationTests.java
Labels: enhancement

#287 Bump Fabric8 Kubernetes client to latest version
  spring-cloud-kubernetes-dependencies/pom.xml
  spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientFilterMetadataTest.java
  spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientFilterTest.java
Labels: in progress, task

#297 Fix NPE when local leader is null
  spring-cloud-kubernetes-leader/src/main/java/org/springframework/cloud/kubernetes/leader/LeadershipController.java
  spring-cloud-kubernetes-leader/src/test/java/org/springframework/cloud/kubernetes/leader/LeadershipControllerTest.java
Labels: waiting-for-triage

#295 Add InfoContributor reporting pod details
  spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/KubernetesAutoConfiguration.java
  spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/KubernetesInfoContributor.java
  spring-cloud-kubernetes-core/src/test/java/org/springframework/cloud/kubernetes/InfoContributorTest.java
Labels: enhancement

#244 Rationalize ConfigMap usage when paths (mounted files) are involved
  README.adoc
  docs/src/main/asciidoc/property-source-config.adoc
  spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java
  spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySourceLocator.java
  spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/PropertySourceUtils.java
  spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapTestUtil.java
  spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsFromFilePathsSpringBootTest.java
  spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsMixedSpringBootTest.java
  spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsTest.java
  spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/example/GreetingController.java
  spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/example/GreetingProperties.java
  spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/example/ResponseMessage.java
  spring-cloud-kubernetes-config/src/test/resources/application-path.yaml
Labels: waiting-for-triage

#286 #233 Initial Istio Awareness implementation
  .circleci/config.yml
  .circleci/istio-test-namespace.yml
  docs/src/main/asciidoc/kubernetes-awareness.adoc
  pom.xml
  spring-cloud-kubernetes-dependencies/pom.xml
  spring-cloud-kubernetes-integration-tests/README.md
  spring-cloud-kubernetes-integration-tests/istio/pom.xml
  spring-cloud-kubernetes-integration-tests/istio/src/main/fabric8/deployment.yml
  spring-cloud-kubernetes-integration-tests/istio/src/main/fabric8/svc.yml
  spring-cloud-kubernetes-integration-tests/istio/src/main/java/org/springframework/cloud/kubernetes/it/IstioApplication.java
  spring-cloud-kubernetes-integration-tests/istio/src/main/resources/bootstrap.yaml
  spring-cloud-kubernetes-integration-tests/istio/src/test/java/org/springframework/cloud/kubernetes/it/ProfilesIT.java
  spring-cloud-kubernetes-integration-tests/istio/src/test/resources/arquillian.xml
  spring-cloud-kubernetes-integration-tests/pom.xml
  spring-cloud-kubernetes-istio/pom.xml
  spring-cloud-kubernetes-istio/src/main/java/org/springframework/cloud/kubernetes/istio/IstioAutoConfiguration.java
  spring-cloud-kubernetes-istio/src/main/java/org/springframework/cloud/kubernetes/istio/IstioBootstrapConfiguration.java
  spring-cloud-kubernetes-istio/src/main/java/org/springframework/cloud/kubernetes/istio/IstioClientProperties.java
  spring-cloud-kubernetes-istio/src/main/java/org/springframework/cloud/kubernetes/istio/utils/MeshUtils.java
  spring-cloud-kubernetes-istio/src/main/resources/META-INF/spring.factories
Labels: in progress
