Repository spring-cloud/spring-cloud-kubernetes, pull requests merged in 2019-06, with the labels that each got.

#401 README update for ConfigMap reload sample
  spring-cloud-kubernetes-examples/kubernetes-reload-example/README.md
  spring-cloud-kubernetes-examples/kubernetes-reload-example/src/k8s/rb.yml
  spring-cloud-kubernetes-examples/kubernetes-reload-example/src/k8s/role.yml
  spring-cloud-kubernetes-examples/kubernetes-reload-example/src/k8s/sa.yml
Labels: feedback-provided

#407 Use maven wrapper in integration tests
  .circleci/config.yml
Labels: waiting-for-triage

#408 Enhance docs about setting Spring profile at bootstrap via ENV Variable
  docs/src/main/asciidoc/property-source-config.adoc
Labels: waiting-for-triage

#404 Enhancment/improve config map property source logging
  spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java
Labels: waiting-for-triage

#410 1.0.x update local leader before notifications
  spring-cloud-kubernetes-examples/kubernetes-leader-election-example/README.md
  spring-cloud-kubernetes-examples/kubernetes-leader-election-example/leader-role.yml
  spring-cloud-kubernetes-examples/kubernetes-leader-election-example/leader-rolebinding.yml
  spring-cloud-kubernetes-examples/kubernetes-leader-election-example/pom.xml
  spring-cloud-kubernetes-examples/kubernetes-leader-election-example/src/main/fabric8/rb.yaml
  spring-cloud-kubernetes-examples/kubernetes-leader-election-example/src/main/fabric8/role.yaml
  spring-cloud-kubernetes-leader/src/main/java/org/springframework/cloud/kubernetes/leader/LeaderAutoConfiguration.java
  spring-cloud-kubernetes-leader/src/main/java/org/springframework/cloud/kubernetes/leader/LeadershipController.java
  spring-cloud-kubernetes-leader/src/test/java/org/springframework/cloud/kubernetes/leader/LeaderAutoConfigurationTests.java
Labels: waiting-for-triage

#406 Obvious Fix: Fix application.yaml file name typo in config source docs
  README.adoc
  docs/src/main/asciidoc/property-source-config.adoc
Labels: documentation

#388 Enhanced Ribbon can support access to workloads through services
  README.adoc
  docs/src/main/asciidoc/ribbon-integration.adoc
  spring-cloud-kubernetes-ribbon/pom.xml
  spring-cloud-kubernetes-ribbon/src/main/java/org/springframework/cloud/kubernetes/ribbon/KubernetesEndpointsServerList.java
  spring-cloud-kubernetes-ribbon/src/main/java/org/springframework/cloud/kubernetes/ribbon/KubernetesRibbonClientConfiguration.java
  spring-cloud-kubernetes-ribbon/src/main/java/org/springframework/cloud/kubernetes/ribbon/KubernetesRibbonMode.java
  spring-cloud-kubernetes-ribbon/src/main/java/org/springframework/cloud/kubernetes/ribbon/KubernetesRibbonProperties.java
  spring-cloud-kubernetes-ribbon/src/main/java/org/springframework/cloud/kubernetes/ribbon/KubernetesServerList.java
  spring-cloud-kubernetes-ribbon/src/main/java/org/springframework/cloud/kubernetes/ribbon/KubernetesServicesServerList.java
  spring-cloud-kubernetes-ribbon/src/test/java/org/springframework/cloud/kubernetes/ribbon/RibbonWithServiceModeTest.java
Labels: in progress, waiting for feedback

#343 Search configMap with active profile name.
  docs/src/main/asciidoc/property-source-config.adoc
  spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java
  spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithActiveProfilesNameSpringBootTest.java
  spring-cloud-kubernetes-config/src/test/resources/application-with-active-profiles-name.yaml
Labels: in progress
