Repository spring-cloud/spring-cloud-kubernetes, pull requests merged in 2019-01, with the labels that each got.

#303 Remove exception from log when configMap can't be read
  spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java
Labels: enhancement

#306 Fix typo that recommends RBAC ensures unauthorized access to Secrets
  docs/src/main/asciidoc/property-source-config.adoc
Labels: documentation

#311 fix wrong link-syntax in readme
  README.adoc
Labels: waiting-for-triage
