Repository spring-cloud/spring-cloud-kubernetes, pull requests merged in 2019-02, with the labels that each got.

#320 Fix potential NPE
  spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClient.java
Labels: bug

#329 ~Updated docs. Added notes about changed behavior of paths property
  README.adoc
  docs/src/main/asciidoc/property-source-config.adoc
Labels: documentation

#335 Assert message "must be null" chnaged to "must not be null"
  spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClient.java
Labels: waiting-for-triage

#334 Add info contributor for leader election.
  spring-cloud-kubernetes-core/pom.xml
  spring-cloud-kubernetes-core/src/test/java/org/springframework/cloud/kubernetes/HealthIndicatorTest.java
  spring-cloud-kubernetes-core/src/test/java/org/springframework/cloud/kubernetes/InfoContributorTest.java
  spring-cloud-kubernetes-leader/pom.xml
  spring-cloud-kubernetes-leader/src/main/java/org/springframework/cloud/kubernetes/leader/LeaderAutoConfiguration.java
  spring-cloud-kubernetes-leader/src/main/java/org/springframework/cloud/kubernetes/leader/LeaderInfoContributor.java
  spring-cloud-kubernetes-leader/src/test/java/org/springframework/cloud/kubernetes/leader/LeaderAutoConfigurationTests.java
  spring-cloud-kubernetes-leader/src/test/java/org/springframework/cloud/kubernetes/leader/LeaderInfoContributorTest.java
Labels: in progress

#317 Fix code snippets in PropertySource config docs
  docs/src/main/asciidoc/property-source-config.adoc
Labels: documentation

#336 Remove redundant groovy tests and replace useful ones with java tests
  pom.xml
  spring-cloud-kubernetes-config/pom.xml
  spring-cloud-kubernetes-config/src/test/groovy/org/springframework/cloud/kubernetes/config/CoreTest.groovy
  spring-cloud-kubernetes-config/src/test/groovy/org/springframework/cloud/kubernetes/config/TestApplication.groovy
  spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/CoreTest.java
  spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/TestApplication.java
  spring-cloud-kubernetes-discovery/pom.xml
  spring-cloud-kubernetes-discovery/src/test/groovy/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientTest.groovy
  spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientTest.java
  spring-cloud-kubernetes-ribbon/pom.xml
  spring-cloud-kubernetes-ribbon/src/test/groovy/io/fabric8/spring/cloud/kubernetes/ribbon/test/RibbonTest.groovy
  spring-cloud-kubernetes-ribbon/src/test/java/org/springframework/cloud/kubernetes/ribbon/RibbonTest.java
  spring-cloud-kubernetes-ribbon/src/test/java/org/springframework/cloud/kubernetes/ribbon/TestApplication.java
Labels: task

#332 Document Spring Boot starters
  docs/src/main/asciidoc/discovery-client.adoc
  docs/src/main/asciidoc/getting-started.adoc
  docs/src/main/asciidoc/ribbon-integration.adoc
  docs/src/main/asciidoc/spring-cloud-kubernetes.adoc
Labels: documentation

#323 Add profile expression support
  spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java
  spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySourceLocator.java
  spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/PropertySourceUtils.java
  spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithProfileExpressionSpringBootTest.java
  spring-cloud-kubernetes-config/src/test/resources/application-with-profiles.yaml
Labels: for team discussion, in progress

#279 Added the instance id to the `KubernetesServiceInstance`
  spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClient.java
  spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesServiceInstance.java
  spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientTest.java
  spring-cloud-kubernetes-integration-tests/discovery/discovery-client/src/main/java/org/springframework/cloud/kubernetes/it/DiscoveryClientApplication.java
  spring-cloud-kubernetes-integration-tests/discovery/tests/src/test/java/org/springframework/cloud/kubernetes/it/ServicesIT.java
Labels: enhancement

#339 document reloader dependency on actuator-autoconfigure
  README.adoc
Labels: documentation

#342 Fix #341 - allow defining a primary port name when multiple ports are defined for a service
  spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClient.java
  spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryProperties.java
  spring-cloud-kubernetes-discovery/src/test/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientTest.java
Labels: waiting-for-triage

#337 Editing pass
  docs/pom.xml
  docs/src/main/asciidoc/discovery-client.adoc
  docs/src/main/asciidoc/discovery-kubernetes-native.adoc
  docs/src/main/asciidoc/examples.adoc
  docs/src/main/asciidoc/kubernetes-awareness.adoc
  docs/src/main/asciidoc/other-resources.adoc
  docs/src/main/asciidoc/pod-health-indicator.adoc
  docs/src/main/asciidoc/property-source-config.adoc
  docs/src/main/asciidoc/ribbon-integration.adoc
  docs/src/main/asciidoc/security-service-accounts.adoc
  docs/src/main/asciidoc/spring-cloud-kubernetes.adoc
Labels: documentation
