Repository spring-cloud/spring-cloud-kubernetes, pull requests merged in 2020-03, with the labels that each got.

#528 Reformat README file
  spring-cloud-kubernetes-examples/kubernetes-hello-world-example/README.md
  spring-cloud-kubernetes-examples/kubernetes-leader-election-example/README.md
  spring-cloud-kubernetes-examples/kubernetes-reload-example/README.md
Labels: documentation

#534 upgrade fabric8 plugin version from 3.5.37 to 4.4.0 fixes gh-532
  pom.xml
Labels: waiting-for-triage

#536 upgrading fabric8 and Istio clients version
  spring-cloud-kubernetes-dependencies/pom.xml
Labels: task

#538 Make order of KubernetesDiscoveryClient configurable - Fixes gh-537
  spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClient.java
  spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryProperties.java
Labels: waiting for feedback

#522 Add spring.cloud.kubernetes.enabled as a metadata
  spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/KubernetesProperties.java
  spring-cloud-kubernetes-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
Labels: waiting for feedback
