Repository spring-cloud/spring-cloud-kubernetes, pull requests merged in 2020-11, with the labels that each got.

#671 Enable the kubernetes profile without API requests
  spring-cloud-kubernetes-client-autoconfig/src/main/java/org/springframework/cloud/kubernetes/client/profile/KubernetesClientProfileEnvironmentPostProcessor.java
  spring-cloud-kubernetes-client-autoconfig/src/test/java/org/springframework/cloud/kubernetes/client/profile/KubernetesClientProfileEnvironmentPostProcessorTests.java
  spring-cloud-kubernetes-fabric8-autoconfig/src/main/java/org/springframework/cloud/kubernetes/fabric8/profile/Fabric8ProfileEnvironmentPostProcessor.java
  spring-cloud-kubernetes-fabric8-autoconfig/src/test/java/org/springframework/cloud/kubernetes/fabric8/profile/Fabric8ProfileEnvironmentPostProcessorTests.java
Labels: enhancement, waiting for feedback

#674 Update anchors for docs
  README.adoc
  docs/src/main/asciidoc/getting-started.adoc
Labels: documentation

#646 fix broken link (missing scheme) and a few typos in hello world example
  spring-cloud-kubernetes-examples/kubernetes-hello-world-example/README.md
Labels: documentation

#625 improvements
  spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/SecretsPropertySourceLocator.java
Labels: waiting for feedback

#676 fix conflicts upon merge
  spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher/src/main/java/org/springframework/cloud/kubernetes/configuration/watcher/ConfigurationWatcherAutoConfiguration.java
  spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-client-config-it/src/test/java/org/springframework/cloud/kubernetes/client/config/it/ConfigMapAndSecretIT.java
Labels: waiting-for-triage

#608 Change "Sleuth" to "Kubernetes" in the reference
  docs/src/main/asciidoc/spring-cloud-kubernetes.adoc
Labels: documentation
