Repository spring-cloud/spring-cloud-kubernetes, pull requests merged in 2020-04, with the labels that each got.

#518 Add labels to the health endpoint
  spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/KubernetesHealthIndicator.java
Labels: enhancement, waiting for feedback

#521 Change getProperty method in order to set the target type
  spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/profile/KubernetesProfileEnvironmentPostProcessor.java
Labels: enhancement

#549 Remove extra space
  spring-cloud-kubernetes-core/src/main/resources/META-INF/spring.factories
Labels: bug

#550 Close the connection of ad hoc kubernetes client
  spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/profile/KubernetesProfileEnvironmentPostProcessor.java
Labels: bug
