Repository spring-cloud/spring-cloud-kubernetes, pull requests merged in 2021-06, with the labels that each got.

#806 Fixing dockerhub links in docs and Readme
  README.adoc
  docs/src/main/asciidoc/spring-cloud-kubernetes-configuration-watcher.adoc
Labels: documentation

#807 #778 Support property 'spring.config.activate.on-profile'.
  spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/Constants.java
  spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/PropertySourceUtils.java
  spring-cloud-kubernetes-commons/src/test/java/org/springframework/cloud/kubernetes/commons/config/PropertySourceUtilsTest.java
Labels: in progress

#803 fabric8 bootstrap configuration changes
  spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/ConditionalOnKubernetesConfigEnabled.java
  spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/ConditionalOnKubernetesSecretsEnabled.java
  spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8BootstrapConfiguration.java
  spring-cloud-kubernetes-fabric8-config/src/test/java/org/springframework/cloud/kubernetes/fabric8/config/Application.java
  spring-cloud-kubernetes-fabric8-config/src/test/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8BootstrapConfigurationTests.java
  spring-cloud-kubernetes-fabric8-config/src/test/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8ConfigUtilsTests.java
Labels: in progress, task

#820 fix-819
  docs/src/main/asciidoc/kubernetes-awareness.adoc
Labels: documentation
