Repository spring-cloud/spring-cloud-kubernetes, pull requests merged in 2022-11, with the labels that each got.

#1127 Add a few tests for KubernetesConfigDataLocationResolver
  spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/KubernetesConfigDataResource.java
  spring-cloud-kubernetes-commons/src/test/java/org/springframework/cloud/kubernetes/commons/config/KubernetesConfigDataLocationResolverTests.java
Labels: waiting-for-triage

#1128 Simplify fabric8 config data location resolver
  spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8ConfigDataLocationResolver.java
Labels: task

#1131 Remove redundant initialization attributes of variables
  spring-cloud-kubernetes-client-loadbalancer/src/main/java/org/springframework/cloud/kubernetes/client/loadbalancer/KubernetesClientServicesListSupplier.java
Labels: task

#1129 Simplify Kubernetes native config data location resolver
  spring-cloud-kubernetes-client-config/src/main/java/org/springframework/cloud/kubernetes/client/config/KubernetesClientConfigContext.java
  spring-cloud-kubernetes-client-config/src/main/java/org/springframework/cloud/kubernetes/client/config/KubernetesClientConfigDataLocationResolver.java
  spring-cloud-kubernetes-client-config/src/test/java/org/springframework/cloud/kubernetes/client/config/KubernetesClientConfigDataLocationResolverTests.java
  spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/KubernetesConfigDataLocationResolver.java
Labels: task

#1137 Remove duplicated examples, remove JKube dependency
  pom.xml
  spring-cloud-kubernetes-examples/kubernetes-hello-world-example/.jdk8
  spring-cloud-kubernetes-examples/kubernetes-hello-world-example/README.md
  spring-cloud-kubernetes-examples/kubernetes-hello-world-example/pom.xml
  spring-cloud-kubernetes-examples/kubernetes-hello-world-example/src/main/java/org/springframework/cloud/kubernetes/examples/App.java
  spring-cloud-kubernetes-examples/kubernetes-hello-world-example/src/main/java/org/springframework/cloud/kubernetes/examples/HelloController.java
  spring-cloud-kubernetes-examples/kubernetes-hello-world-example/src/main/resources/application.properties
  spring-cloud-kubernetes-examples/kubernetes-hello-world-example/src/test/java/org/springframework/cloud/kubernetes/examples/ApplicationTestIT.java
  spring-cloud-kubernetes-examples/kubernetes-hello-world-example/src/test/resources/logback-test.xml
  spring-cloud-kubernetes-examples/kubernetes-leader-election-example/README.md
  spring-cloud-kubernetes-examples/kubernetes-leader-election-example/pom.xml
  spring-cloud-kubernetes-examples/kubernetes-loadbalancer-example/README.md
  spring-cloud-kubernetes-examples/kubernetes-loadbalancer-example/greeting-service/pom.xml
  spring-cloud-kubernetes-examples/kubernetes-loadbalancer-example/greeting-service/src/main/fabric8/route.yml
  spring-cloud-kubernetes-examples/kubernetes-loadbalancer-example/greeting-service/src/main/java/org/springframework/cloud/kubernetes/examples/GreetingController.java
  spring-cloud-kubernetes-examples/kubernetes-loadbalancer-example/greeting-service/src/main/java/org/springframework/cloud/kubernetes/examples/GreetingServiceApplication.java
  spring-cloud-kubernetes-examples/kubernetes-loadbalancer-example/greeting-service/src/main/java/org/springframework/cloud/kubernetes/examples/NameService.java
  spring-cloud-kubernetes-examples/kubernetes-loadbalancer-example/greeting-service/src/main/resources/application.yml
  spring-cloud-kubernetes-examples/kubernetes-loadbalancer-example/name-service/pom.xml
  spring-cloud-kubernetes-examples/kubernetes-loadbalancer-example/name-service/src/main/fabric8/route.yml
  spring-cloud-kubernetes-examples/kubernetes-loadbalancer-example/name-service/src/main/java/org/springframework/cloud/kubernetes/examples/NameController.java
  spring-cloud-kubernetes-examples/kubernetes-loadbalancer-example/name-service/src/main/java/org/springframework/cloud/kubernetes/examples/NameServiceApplication.java
  spring-cloud-kubernetes-examples/kubernetes-loadbalancer-example/name-service/src/main/resources/application.yml
  spring-cloud-kubernetes-examples/kubernetes-loadbalancer-example/pom.xml
  spring-cloud-kubernetes-examples/kubernetes-reload-example/.jdk8
  spring-cloud-kubernetes-examples/kubernetes-reload-example/README.md
  spring-cloud-kubernetes-examples/kubernetes-reload-example/config-map.yml
  spring-cloud-kubernetes-examples/kubernetes-reload-example/pom.xml
  spring-cloud-kubernetes-examples/kubernetes-reload-example/src/k8s/rb.yml
  spring-cloud-kubernetes-examples/kubernetes-reload-example/src/k8s/role.yml
  spring-cloud-kubernetes-examples/kubernetes-reload-example/src/k8s/sa.yml
  spring-cloud-kubernetes-examples/kubernetes-reload-example/src/main/java/org/springframework/cloud/kubernetes/examples/App.java
  spring-cloud-kubernetes-examples/kubernetes-reload-example/src/main/java/org/springframework/cloud/kubernetes/examples/DummyConfig.java
  spring-cloud-kubernetes-examples/kubernetes-reload-example/src/main/java/org/springframework/cloud/kubernetes/examples/MyBean.java
  spring-cloud-kubernetes-examples/kubernetes-reload-example/src/main/java/org/springframework/cloud/kubernetes/examples/MyConfig.java
  spring-cloud-kubernetes-examples/kubernetes-reload-example/src/main/resources/application.yaml
  spring-cloud-kubernetes-examples/kubernetes-reload-example/src/main/resources/bootstrap.yaml
  spring-cloud-kubernetes-examples/kubernetes-reload-example/src/main/resources/logback.xml
  spring-cloud-kubernetes-examples/kubernetes-reload-example/src/main/resources/old-application.properties
  spring-cloud-kubernetes-examples/pom.xml
Labels: task

#1138 Simplify fabric8 catalog watcher
  spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/discovery/EndpointNameAndNamespace.java
  spring-cloud-kubernetes-fabric8-discovery/src/main/java/org/springframework/cloud/kubernetes/fabric8/discovery/KubernetesCatalogWatch.java
  spring-cloud-kubernetes-fabric8-discovery/src/main/java/org/springframework/cloud/kubernetes/fabric8/discovery/ServicePortSecureResolver.java
  spring-cloud-kubernetes-fabric8-discovery/src/test/java/org/springframework/cloud/kubernetes/fabric8/discovery/KubernetesCatalogWatchTest.java
  spring-cloud-kubernetes-fabric8-discovery/src/test/java/org/springframework/cloud/kubernetes/fabric8/discovery/ServicePortSecureResolverTest.java
Labels: task

#1140 Fix 1139
  spring-cloud-kubernetes-fabric8-autoconfig/src/main/java/org/springframework/cloud/kubernetes/fabric8/Fabric8Utils.java
  spring-cloud-kubernetes-fabric8-autoconfig/src/test/java/org/springframework/cloud/kubernetes/fabric8/Fabric8UtilsTests.java
  spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8ConfigMapPropertySourceLocator.java
  spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8ConfigUtils.java
  spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8SecretsPropertySourceLocator.java
  spring-cloud-kubernetes-fabric8-config/src/test/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8ConfigUtilsTests.java
  spring-cloud-kubernetes-fabric8-discovery/src/main/java/org/springframework/cloud/kubernetes/fabric8/discovery/KubernetesCatalogWatch.java
  spring-cloud-kubernetes-fabric8-discovery/src/main/java/org/springframework/cloud/kubernetes/fabric8/discovery/KubernetesCatalogWatchAutoConfiguration.java
  spring-cloud-kubernetes-fabric8-discovery/src/test/java/org/springframework/cloud/kubernetes/fabric8/discovery/Fabric8KubernetesCatalogWatchTests.java
  spring-cloud-kubernetes-fabric8-discovery/src/test/java/org/springframework/cloud/kubernetes/fabric8/discovery/KubernetesCatalogWatchTest.java
Labels: enhancement

#1144 [docs] Add missing blank line before lists
  docs/src/main/asciidoc/property-source-config.adoc
Labels: documentation

#1145 README.adoc link improvements;
  README.adoc
Labels: documentation

#1142 Remove redundant dependencies
  spring-cloud-kubernetes-commons/pom.xml
Labels: bug

#1152 load docker image before test for CatalogWatchIT
  spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-fabric8-client-catalog-watcher/src/test/java/org/springframework/cloud/kubernetes/fabric8/catalog/watch/CatalogWatchIT.java
  spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-fabric8-client-catalog-watcher/src/test/resources/busybox/deployment.yaml
  spring-cloud-kubernetes-test-support/src/main/java/org/springframework/cloud/kubernetes/integration/tests/commons/Commons.java
Labels: bug

#1153 fix wiremock dependency
  .github/workflows/composites/build-controllers-project/action.yaml
  spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher/pom.xml
  spring-cloud-kubernetes-integration-tests/spring-cloud-kubernetes-fabric8-client-catalog-watcher/src/test/java/org/springframework/cloud/kubernetes/fabric8/catalog/watch/CatalogWatchIT.java
Labels: bug
