Repository spring-cloud/spring-cloud-kubernetes, pull requests merged in 2022-02, with the labels that each got.

#967 clean-up
  spring-cloud-kubernetes-client-autoconfig/src/test/java/org/springframework/cloud/kubernetes/client/KubernetesClientActuatorTests.java
  spring-cloud-kubernetes-commons/src/test/java/org/springframework/cloud/kubernetes/commons/config/KubernetesBootstrapConfigurationTests.java
  spring-cloud-kubernetes-fabric8-config/src/test/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8ConfigMapPropertySourceLocatorRetryTests.java
Labels: task, waiting-for-triage

#966 deps: bump JKube to 1.6.0
  pom.xml
  spring-cloud-kubernetes-integration-tests/pom.xml
Labels: waiting-for-triage

#974 clean-up
  .circleci/config.yml
  spring-cloud-kubernetes-integration-tests/load-balancer/src/test/java/org/springframework/cloud/kubernetes/fabric8/loadbalancer/LoadBalancerAllNamespacesTests.java
  spring-cloud-kubernetes-integration-tests/load-balancer/src/test/java/org/springframework/cloud/kubernetes/fabric8/loadbalancer/LoadBalancerTests.java
  spring-cloud-kubernetes-integration-tests/load-balancer/src/test/java/org/springframework/cloud/kubernetes/fabric8/loadbalancer/LoadBalancerWithServiceTests.java
  spring-cloud-kubernetes-integration-tests/simple-core/pom.xml
Labels: task

#980 log with warn fix 978
  spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8ConfigUtils.java
Labels: task
