Repository spring-cloud/spring-cloud-kubernetes, pull requests merged in 2024-02, with the labels that each got.

#1566 Adjust configmap priority order
  docs/src/main/asciidoc/property-source-config.adoc
  spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/SourceDataEntriesProcessor.java
  spring-cloud-kubernetes-commons/src/test/java/org/springframework/cloud/kubernetes/commons/config/SourceDataEntriesProcessorOrderedPropertiesTests.java
  spring-cloud-kubernetes-commons/src/test/java/org/springframework/cloud/kubernetes/commons/config/SourceDataEntriesProcessorSortedTests.java
Labels: waiting-for-triage

#1578 Move to common annotation for load balancer enabled
  spring-cloud-kubernetes-client-loadbalancer/src/main/java/org/springframework/cloud/kubernetes/client/loadbalancer/KubernetesClientLoadBalancerAutoConfiguration.java
  spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/loadbalancer/ConditionalOnKubernetesLoadBalancerEnabled.java
  spring-cloud-kubernetes-fabric8-loadbalancer/src/main/java/org/springframework/cloud/kubernetes/fabric8/loadbalancer/Fabric8LoadBalancerAutoConfiguration.java
Labels: enhancement

#1579 Minor simplification in load balancer supplier
  spring-cloud-kubernetes-client-loadbalancer/src/main/java/org/springframework/cloud/kubernetes/client/loadbalancer/KubernetesClientServicesListSupplier.java
Labels: bug

#1580 discoveryserver: fixes deployment yaml and adds notes about use of Eureka's port
  docs/modules/ROOT/pages/spring-cloud-kubernetes-discoveryserver.adoc
Labels: documentation
